### ISSUE TITLE
CAN NOT find the training tool tab: TypeError: unsupported operand type(s) for |:

### ISSUE THREAD

**Issue by Gonglin95** [liasece/sd-webui-train-tools#1]
安装重启后看不到training tool
After installing, and restarting,  i CAN NOT find the training tool at all.
Anyone encounters the same problem?
<img width="1212" alt="WeChat31c0855ad49a851764a248c624d00d8b" src="https://user-images.githubusercontent.com/69379735/226299515-c4f0baf4-9a89-40c6-b7b9-3911d43d06b7.png">

**Comment by liasece** [comment]
`|` was added in python 3.10. what's your python version? `python --version`

**Comment by Gonglin95** [comment]
> `|` was added in python 3.10. what's your python version? `python --version`

Thank you for your kind reply.  I used python 3.9. It seems the version of PYTHON caused this problem. I'll try to update my python.

**Comment by ronniechoyy** [comment]
Same here, but I'm in python 3.10.6 still not showing

**Comment by liasece** [comment]
> Same here, but I'm in python 3.10.6 still not showing

What is the error message?

**Comment by tanzhu** [comment]
For me, I got the error message 'ModuleNotFoundError: No module named 'diffusers'' after restarted ui, with python 3.10.6. 
So I directly install the lost module using 'pip install diffusers' in venv.
It works.
