### ISSUE TITLE
reg image 识别不到

### ISSUE THREAD

**Issue by semicoder** [liasece/sd-webui-train-tools#13]
found directory /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/outputs/train_tools/projects/xx/versions/v2/dataset/processed/28_xx contains 20 image files
500 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした

**Comment by liasece** [comment]
你的正则图像放在哪个目录下？

**Comment by semicoder** [comment]
> 你的正则图像放在哪个目录下
新建的 reg 目录
![image](https://user-images.githubusercontent.com/6425322/230526694-386a126f-9f3f-4363-bf35-91fbe08c9ab0.png)

**Comment by Thetail001** [comment]
我也碰到了这个问题

**Comment by liasece** [comment]
reg 目录下是什么结构？正确的 reg 子目录结构应该是和待训练数据拥有同样关键词的目录，例如：

`dataset/processed/40_object`

对应的正则化图片目录为：

`dataset/reg/10_object`

**Comment by Thetail001** [comment]
> reg 目录下是什么结构？正确的 reg 子目录结构应该是和待训练数据拥有同样关键词的目录，例如：
> 
> `dataset/processed/40_object`
> 
> 对应的正则化图片目录为：
> 
> `dataset/reg/10_object`

好吧，确实是少了XX_object这个目录，谢谢。（希望作者能在说明里修改下说法，原来的说明让人以为是直接放到/reg下就可以了，还有作者大大以后还会更新提供可以调整更多参数的版本吗？有一些参数我现在找不到要在哪里设置，比如说分辨率啥的
