### ISSUE TITLE
这个插件支持Keep token吗

### ISSUE THREAD

**Issue by CloudyLouis** [liasece/sd-webui-train-tools#15]

**Comment by liasece** [comment]
当你需要定制你的 Token 或者叫提示文本或者叫训练图Tag时，不建议使用这种统一参数，而是去使用专业的管理训练图 tag 的插件或其他工具 如 https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor 。

因为通常需要这种精细微调的工作不该用一个影响整个数据集统一的参数控制，而是真正地去微调每个子训练集的参数。
