### ISSUE TITLE
使用admw8bit时，linux机器会报/root/bin无权限

### ISSUE THREAD

**Issue by starinskycc** [liasece/sd-webui-train-tools#16]
如题，使用lion可以正常，请问是什么原因啊

**Comment by liasece** [comment]
具体是哪个文件无权限？先检查报错的目标文件及其父文件夹的权限

**Comment by starinskycc** [comment]
![image](https://user-images.githubusercontent.com/6244330/231330299-48cb81c8-1eb8-49a3-a0d7-3bd275d490a4.png)

**Comment by starinskycc** [comment]
/root/下都没有bin这个文件夹

**Comment by starinskycc** [comment]
另外启动时带了xformers，勾选 user xformers也会报错
![image](https://user-images.githubusercontent.com/6244330/231331008-df997dfe-aacd-408b-ae68-10b96733cc08.png)

**Comment by liasece** [comment]
> 另外启动时带了xformers，勾选 user xformers也会报错
> ![image](https://user-images.githubusercontent.com/6244330/231331008-df997dfe-aacd-408b-ae68-10b96733cc08.png)

关掉其他训练插件，不同训练插件见的依赖有冲突

**Comment by liasece** [comment]
> ![image](https://user-images.githubusercontent.com/6244330/231330299-48cb81c8-1eb8-49a3-a0d7-3bd275d490a4.png)

这个报错意思是它找不到 cuda 运行时，你的 cuda 安装环境变量有问题。在cuda安装完成时，信息里提示了要设置的环境变量
