### ISSUE TITLE
Is this for Automatic1111?

### ISSUE THREAD

**Issue by DiggyDre** [liasece/sd-webui-train-tools#17]
I installed this but it is not showing up anywhere.

**Comment by liasece** [comment]
Are there any error messages on the webui command line console?

**Comment by DiggyDre** [comment]
![WebUI](https://user-images.githubusercontent.com/127576526/232777761-799cdeab-b0f7-47aa-a0af-dfbc913cebcc.jpg)

**Comment by liasece** [comment]
Your webui storage path has spaces in it, which causes some unintended behavior. You just need to remove the spaces in "D:\AI\STABLE DIFFUSION - AUTOMATIC 1111 - 1_7_0"

**Comment by DiggyDre** [comment]
That breaks my entire install

**Comment by liasece** [comment]
> That breaks my entire install

What does it mean? You just need to change the " STABLE DIFFUSION - AUTOMATIC 1111 - 1_7_0" folder name, remove its spaces.

**Comment by DiggyDre** [comment]
I tried that and then my A1111 doesn't open until I put the spaces back. I ended up just doing a fresh install into a folder that doesn't have spaces and everything seems fine now.
