### ISSUE TITLE
页面上训练的参数和Lora脚本训练的参数不一致吗？

### ISSUE THREAD

**Issue by MiDark** [liasece/sd-webui-train-tools#18]
感谢作者提供了这么棒的扩展~
我测试了使用该工具（[sd-webui-train-tools](https://github.com/liasece/sd-webui-train-tools)）训练60张素材和使用脚本（[lora-scripts](https://github.com/Akegarasu/lora-scripts)）训练60张相同素材

**结果使用页面工具的训练结果完全不拟合，通过脚本训练的结果效果较好，麻烦帮忙看下问题可能出现在哪里？**

使用脚本默认配置
```
$max_train_epoches = 10 
$save_every_n_epochs = 1 
$lr = "1e-4"
$network_dim = 32 
$network_alpha = 32
$clip_skip = 2 
$use_8bit_adam = 1 
$use_lion = 0 
```
设置扩展页面上的配置
```
Clip skip :2
Save every n epochs:1
Batch size:1
Number of epochs:10
Learning rate:0.0001
Net dim:32
Alpha:32
Optimizer type:
Mixed precision:fp16
```

运行过程中的日志：
![image](https://user-images.githubusercontent.com/8789351/232287421-808e1036-66be-4eac-85e4-d5f244858dfc.png)
![image](https://user-images.githubusercontent.com/8789351/232287132-fe05052e-2b15-4795-8e66-4f50688110d4.png)

从日志看存在的问题：
1.通过页面上传的60张素材，最后文件夹名字是8_xx，虽然素材都处理了，但是没有正确识别数量
2.训练的步数远小于预期（4800<36000）

另外 https://github.com/kohya-ss/sd-scripts 已在本仓库引用版本后更新了较多内容，请评估下是否可以更新到最新版本，Thanks~

**Comment by liasece** [comment]
你说的两个问题其实是一个，你可以直接修改文件的文件夹名字，也可以在上传训练图片时设置 "Train number of repetitions" 。

另外，60张素材上传完后，如果做镜像增广就 *2 有 120 张训练数据，然后8_xx意思是训练8次就是 960，如果batch size 是2那就是一个 epoch 训练 480 步，如果你训练 10 epoch 就是总计 4800 步。

所以如果是训练步数不足，有很多方式可以解决，你可以提高 8_xx 这个 8，也可以提高训练 epoch 数。

**Comment by MiDark** [comment]
了解了，感谢解答。
