### ISSUE TITLE
新增参数不支持

### ISSUE THREAD

**Issue by hyd998877** [liasece/sd-webui-train-tools#19]
min_snr_gamma，weighted_captions

**Comment by liasece** [comment]
see https://github.com/liasece/sd-webui-train-tools?tab=readme-ov-file#%E9%AB%98%E7%BA%A7-sd_script-%E5%8F%82%E6%95%B0%E8%BF%BD%E5%8A%A0%E6%88%96%E8%A6%86%E7%9B%96
