### ISSUE TITLE
感谢作者的插件，非常好用，有一点点建议

### ISSUE THREAD

**Issue by hyd998877** [liasece/sd-webui-train-tools#20]
1，可否改成支持上传图片但不进行任何处理，因为最终还是需要手动打tag，经常是tag已经打好
2，如果可以把训练的所有参数列在一个文档里面，然后gradio创建一个textox进行展示，用户需要哪个就改哪个，如果哪里sd新增了参数用户也可以自己手动添加
3，可否让这个插件也可以独立webui单独运行，因为sd的diffusers版本和dreambooth版本会冲突
建议不一定成熟，可以随时关闭这个issues

**Comment by liasece** [comment]
谢谢。
1. 你可以直接在文件管理器修改训练目录下的图片或者目录，不一定需要在插件里上传dataset。
2. 和插件初衷相悖，不过目前支持了追加或覆盖 sd_script 参数的功能，如果是强技术人员，使用该方式覆盖参数即可。
3. 和插件初衷相悖。
