### ISSUE TITLE
Error running install.py

### ISSUE THREAD

**Issue by Ryosuke17** [liasece/sd-webui-train-tools#22]
I am Japanese. Sorry for my poor English. I'm using a translation software, so I'm sorry if I'm wrong.
I have read the other threads, but I couldn't figure out where to enter the commands and such.
I installed sd-webui-train-tools, but the torein tools tab does not appear.
The error message is as follows

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]

Error running install.py for extension D:\GenerativeAI\webui\extensions\sd-webui-train-tools.
Command: "D:\GenerativeAI\system\python\python.exe" "D:\GenerativeAI\webui\extensions\sd-webui-train-tools\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "D:\GenerativeAI\webui\extensions\sd-webui-train-tools\install.py", line 8, in <module>
    repo.git.submodule("update", "--init", "--recursive", "--force")
  File "D:\GenerativeAI\system\python\lib\site-packages\git\cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "D:\GenerativeAI\system\python\lib\site-packages\git\cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
  File "D:\GenerativeAI\system\python\lib\site-packages\git\cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git submodule update --init --recursive --force
  stderr: 'git: 'submodule' is not a git command. See 'git --help'.'

Launching Web UI with arguments: --xformers
ControlNet v1.1.106
ControlNet v1.1.106
Error loading script: train_tools.py
Traceback (most recent call last):
  File "D:\GenerativeAI\webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\GenerativeAI\webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\GenerativeAI\webui\extensions\sd-webui-train-tools\scripts\train_tools.py", line 7, in <module>
    from liasece_sd_webui_train_tools.ui import *
  File "D:\GenerativeAI\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ui.py", line 16, in <module>
    from liasece_sd_webui_train_tools.train_ui import *
  File "D:\GenerativeAI\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train_ui.py", line 10, in <module>
    from liasece_sd_webui_train_tools import train
  File "D:\GenerativeAI\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train.py", line 8, in <module>
    from liasece_sd_webui_train_tools.ArgsList import ArgStore
  File "D:\GenerativeAI\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ArgsList.py", line 22, in <module>
    import liasece_sd_webui_train_tools.sd_scripts.train_network as train_network
ModuleNotFoundError: No module named 'liasece_sd_webui_train_tools.sd_scripts.train_network'

**Comment by liasece** [comment]
same #14

try `venv/Scripts/Python.exe launch.py --listen --port 7860 --xformers --no-half-vae --enable-insecure-extension-access`

**Comment by Ryosuke17** [comment]
> same #14
> 
> try `venv/Scripts/Python.exe launch.py --listen --port 7860 --xformers --no-half-vae --enable-insecure-extension-access`

thank you so much.
Where do I type that? Git Bash in webui folder?

**Comment by liasece** [comment]
> Where do I type that? Git Bash in webui folder?

Yes.

**Comment by Ryosuke17** [comment]
> > Where do I type that? Git Bash in webui folder?
> 
> Yes.

thank you.
I did but did not problem was never solved.

1st
PC_User@DESKTOP-5ANHQRL MINGW64 /d/GenerativeAI/webui (master)
$ venv/Scripts/Python.exe launch.py --listen --port 7860 --xformers --no-half-vae --enable-insecure-extension-access
No Python at '"C:\Users\PC_User\AppData\Local\Programs\Python\Python311\python.exe'

i had python 310 did not have 311.so after this I got pyson 311.
then tryed this again
venv/Scripts/Python.exe launch.py --listen --port 7860 --xformers --no-half-vae --enable-insecure-extension-access

2nd
PC_User@DESKTOP-5ANHQRL MINGW64 /d/GenerativeAI/webui (master)
$ venv/Scripts/Python.exe launch.py --listen --port 7860 --xformers --no-half-e --enable-insecure-extension-access
============================================================================================================
INCOMPATIBLE PYTHON VERSION

This program is tested with 3.10.6 Python, but you have 3.11.0.
If you encounter an error with "RuntimeError: Couldn't install torch." message
or any other error regarding unsuccessful package (library) installation,
please downgrade (or upgrade) to the latest version of 3.10 Python
and delete current Python and "venv" folder in WebUI's directory.

You can download 3.10 Python from here: https://www.python.org/downloads/relea/python-3109/

Alternatively, use a binary release of WebUI: https://github.com/AUTOMATIC1111table-diffusion-webui/releases

Use --skip-python-version-check to suppress this warning.
============================================================================================================
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/117
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+c17 (from versions: 2.0.0, 2.0.0+cu117)
ERROR: No matching distribution found for torch==1.13.1+cu117

[notice] A new release of pip available: 22.3.1 -> 23.1.1
[notice] To update, run: D:\GenerativeAI\webui\venv\Scripts\python.exe -m pip stall --upgrade pip
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing torch and torchvision
Traceback (most recent call last):
  File "D:\GenerativeAI\webui\launch.py", line 355, in <module>
    prepare_environment()
  File "D:\GenerativeAI\webui\launch.py", line 257, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", ouldn't install torch", live=True)
  File "D:\GenerativeAI\webui\launch.py", line 81, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "D:\GenerativeAI\webui\venv\Scripts\Python.exe" -m pip install torch=.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytor.org/whl/cu117
Error code: 1

**Comment by liasece** [comment]
How did you start AUTOMATIC1111/stable-diffusion-webui before using this extension?

> $ venv/Scripts/Python.exe launch.py --listen --port 7860 --xformers --no-half-vae --enable-insecure-extension-access
> No Python at '"C:\Users\PC_User\AppData\Local\Programs\Python\Python311\python.exe'

If you were able to start AUTOMATIC1111/stable-diffusion-webui correctly before, this error should not have appeared. Maybe because python venv was not initialized successfully?

**Comment by Ryosuke17** [comment]
> How did you start AUTOMATIC1111/stable-diffusion-webui before using this extension?
> 
> > $ venv/Scripts/Python.exe launch.py --listen --port 7860 --xformers --no-half-vae --enable-insecure-extension-access
> > No Python at '"C:\Users\PC_User\AppData\Local\Programs\Python\Python311\python.exe'
> 
> If you were able to start AUTOMATIC1111/stable-diffusion-webui correctly before, this error should not have appeared. Maybe because python venv was not initialized successfully?

thank you kind reply.
I got and using from this.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.0.0-pre

**Comment by chenshaoju** [comment]
wrong folder, sorry for disturb.
