### ISSUE TITLE
Cannot find the directory where train data is stored

### ISSUE THREAD

**Issue by tomato-ga** [liasece/sd-webui-train-tools#25]
I always use it with docker. Thank you!

I used this train-tools to create Lora.

Then, it says that it saved the safetensors file in the following directory, but I can't find it by using find or grep commands.

`outputs/train_tools/projects/likeface/versions/v1/trains/chilled_remix_v1vae-bs-1-ep-20-op-Lion-lr-0_0001-net-128-ap-64/likeface-v 1.safetensors`

The `data` and `output` directories are there, but the `outputs` directory was not found.

If you are running stable diffusion in docker, does anyone know where it is stored?

<img width="587" alt="スクリーンショット 2023-05-04 13 08 43" src="https://user-images.githubusercontent.com/52771764/236110794-5ce9c2f8-d929-44d3-9dc0-416fa62ab426.png">

**Comment by liasece** [comment]
`outputs`are relative directories, relative to your stable diffusion startup directory. You can probably find it in the directory pointed to by DockerFile `WORKDIR`

**Comment by tomato-ga** [comment]
thx!

Since we only had the docker compose file, let's test it with the following changes.

```
version: '3.9'

x-base_service: &base_service
    ports:.
      - "7860:7860"
    volumes: .
      - &v1 . /data:/data
      - &v2 . /output:/output
      - &v3 . /outputs:/outputs
    stop_signal: SIGINT
    deploy: /outputs:/outputs
      resources: /output:/outputs &v3 .
        reservations: devices: /devices: /outputs: /outputs: /devices
          devices: nvidia
              - driver: nvidia
                device_ids: ['0'].
                capabilities: [gpu]
```
