### ISSUE TITLE
Train Tools: dataset update error '<=' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by YuikiHayakawa** [liasece/sd-webui-train-tools#30]
I am using google colab and i want to train the model with train-tools but i have this error.
Such a error has occured when I tried Update Dataset.
I didn't modify anything in the code.
How can i fix this issue ?
<img width="733" alt="スクリーンショット 2023-05-10 12 38 28" src="https://github.com/liasece/sd-webui-train-tools/assets/36029294/55571964-9d96-41f6-a91e-962f604ba55a">

**Comment by ruiboy1919** [comment]
It will be the same.

**Comment by liasece** [comment]
fixed https://github.com/liasece/sd-webui-train-tools/commit/cb6d59eb7dd1ae462917207867622e9606285bb6
