### ISSUE TITLE
the loading is in the everywhere

### ISSUE THREAD

**Issue by tzwm** [liasece/sd-webui-train-tools#32]
OS: ubuntu
stable diffusion webui: updated: 2023-05-14, hash: 89f9faa6
train tools: b8dc7712be71370cb80965b820bfb95d2ea00838
console:
```
To create a public link, set `share=True` in `launch()`.
Startup time: 23.4s (import torch: 2.8s, import gradio: 0.7s, import ldm: 0.8s, other imports: 0.8s, load scripts: 16.7s, create ui: 1.2s, gradio launch: 0.2s, scripts app_started_callback: 0.1s).
Train Tools: get_project_list: outputs/train_tools/projects/test
Train Tools: get_project_version_list: outputs/train_tools/projects/test/versions/v1
Train Tools: ui_refresh_project: ['test']
```

<img width="1494" alt="image" src="https://github.com/liasece/sd-webui-train-tools/assets/828837/e36349ab-3f84-4bca-b947-7f5f37618c8c">

**Comment by liasece** [comment]
Same https://github.com/liasece/sd-webui-train-tools/issues/4 . Try adding `--no-gradio-queue` to the launch webui command.

**Comment by tzwm** [comment]
> Same #4 . Try adding `--no-gradio-queue` to the launch webui command.

Thanks!
