### ISSUE TITLE
Multi-dataset training problem：

### ISSUE THREAD

**Issue by Major1994** [liasece/sd-webui-train-tools#38]
Hi 我在训练lora 的时候遇到问题：
1. 想用多个数据集：上传一个新的数据集图片，但是旧的数据集会被删掉
2. Preprocess images 中： 用blip或deepbooru 生成的caption，想在train tool 中修改，想问下该怎么操作。

谢谢 🙏

**Comment by liasece** [comment]
1. 现在一个训练里只支持一个数据集，也就是一个lora只支持一个触发词
2. 看 [这里](https://github.com/liasece/sd-webui-train-tools#%E6%80%8E%E6%A0%B7%E7%AE%A1%E7%90%86%E8%AE%AD%E7%BB%83%E5%9B%BE%E7%89%87%E7%94%9F%E6%88%90%E7%9A%84-tag)
