### ISSUE TITLE
Lora训练报错

### ISSUE THREAD

**Issue by njugcy** [liasece/sd-webui-train-tools#39]
在跑模型的时候，遇到了这样的问题：
MemoryError: Out of memory interning an attribute name
然后会出现一系列系统提示显示有问题

**Comment by njugcy** [comment]
会报OSError: [WinError 1455] 页面文件太小，无法完成操作。的问题，不过我也不知道怎么配置页面大小，出这个问题以后浏览器都会几乎崩溃

**Comment by liasece** [comment]
https://blog.csdn.net/weixin_46133643/article/details/125042903
