### ISSUE TITLE
上传图片按钮

### ISSUE THREAD

**Issue by jingzhengli** [liasece/sd-webui-train-tools#42]
1）处理后的图片保存在.../processed/.    后面需要训练的图片在./reg/..   但是这个需要训练的路径没有办法修改啊，怎么把处理的路径改成训练的路径呢？
![image](https://github.com/liasece/sd-webui-train-tools/assets/40593161/3f49327f-8402-4eb9-80fd-39db63600056)

**Comment by liasece** [comment]
不需要修改，如果你想自定义训练数据，直接替换目录下的文件即可，不一定要从插件的dataset里上传
