### ISSUE TITLE
Cannot install extension

### ISSUE THREAD

**Issue by wangyiwei2015** [liasece/sd-webui-train-tools#47]
Platform: macOS 13.5 on M2 Pro
Automatic1111 SD-WebUI: v1.5.4
Python: v3.10.12
torch: v1.12.1

The WebUI works well, but when installing this extension from URL it stucks showing "Loading" below the install button.
No output in terminal.

Then, stuck in "installing requirements for web ui" on restart.
If this extension is manually removed from the dir, the Web UI runs normally.

**Comment by liasece** [comment]
Check your network environment? Installation problems should only be due to network issues
