### ISSUE TITLE
HOW TO FIX PLS ?

### ISSUE THREAD

**Issue by yudas5** [liasece/sd-webui-train-tools#5]
![Capture](https://user-images.githubusercontent.com/72172666/228875894-9fc685d6-aa87-46e4-8f11-805508ed75b6.PNG)

**Comment by liasece** [comment]
What version of xformer are you using? `pip list | grep xformer` , I'm at 0.0.16rc425

**Comment by yudas5** [comment]
xformers version 0.0.17+b6be33a.d20230315

**Comment by liasece** [comment]
I failed to reproduce the problem. You can try reinstalling the dependency by performing the installation in the sd-webui directory:

`pip install -r requirements.txt`

Perhaps, you need to reinstall xformers

`pip install xformers==0.0.17`

**Comment by liasece** [comment]
Are there any other training plugins installed? It seems same #6 

In short, disable other plugins to prevent dependency conflicts.
