### ISSUE TITLE
训练室内设计图片，一般参数用什么啊

### ISSUE THREAD

**Issue by starinskycc** [liasece/sd-webui-train-tools#7]
装修设计的效果图，图片示例如下
![image](https://user-images.githubusercontent.com/6244330/229337313-ff16a6f4-547a-4eda-8ff3-68a950f1e8fd.png)
一般需要怎么设置参数啊？准备多少张图片，以及角度什么的？

**Comment by starinskycc** [comment]
我测试了一下，训练出来的图片里面的东西全是变形的。

**Comment by liasece** [comment]
Lora 一般是训练画风或者对象，不适用于场景。

如果想要控制场景，可以直接使用 ControlNet 的语义分割功能。而不是训练一个Lora。

如果你想训练风格如 欧式风格/极简轻奢/古典木质 ，那么只需准备这些风格的内装图直接练即可。

核心是：跟场景无关，只和风格相关。想要控制场景，使用 ControlNet 的语义分割。
